export const texts = {
	RU: {
		home: 'Главная',
		history: 'История',
		settings: 'Настройки',
		logout: 'Выйти',
		selectFilter: 'ВЫБОР ФИЛЬТРОВ',
		filterCardLogo: 'Лого',
		filterCardIsOriginal: 'Только оригиналы',
		filterCardIsNotOriginal: 'Оригиналы и аналоги',
		filterCardDeliveryTime: 'Срок поставки',
		filterCardDepthAnalogueSearch: 'Глубина поиска аналога',
		filterCardDepthSelectionByTheFirstFilter:
			'Глубина отбора по первому фильтру',
		uploadingData: 'ЗАГРУЗКА ДАННЫХ',
		dragAndDropInput: `Щелкните или перетащите файл в эту область<br/> для загрузки.<br/>Загружаемый файл должен быть в формате xlsx.<br/>Файл будет автоматически загружен в систему.`,
		downloadTemplate: 'Скачать шаблон',
		processManagement: 'УПРАВЛЕНИЕ ПРОЦЕССОМ',
		Available: 'Доступно',
		logoIsNotUsed: 'не используется',
	},
	EN: {
		home: 'Home',
		history: 'History',
		settings: 'Settings',
		logout: 'Logout',
		selectFilter: 'FILTER SELECTION',
		filterCardLogo: 'Logo',
		filterCardIsOriginal: 'Originals only',
		filterCardIsNotOriginal: 'Originals and analogs',
		filterCardDeliveryTime: 'Delivery time',
		filterCardDepthAnalogueSearch: 'Depth of analogue search',
		filterCardDepthSelectionByTheFirstFilter:
			'Depth of selection by the first filter',
		uploadingData: 'UPLOADING DATA',
		dragAndDropInput:
			'Click or drag the file to this area to upload.<br/>The uploaded file must be in xlsx format. The file will<br/> be automatically uploaded to the system.',
		downloadTemplate: 'Download template',
		processManagement: 'PROCESS MANAGEMENT',
		Available: 'Available',
		logoIsNotUsed: 'is not used',
	},
}

export const historyTexts = {
	RU: {
		history: 'История',
		date: 'Дата',
		filters: 'Фильтры',
		dataBeforeParsing: 'Данные до парсинга',
		dataAfterParsing: 'Данные после парсинга',
		downloadFile: 'Скачать файл',
		viewFile: 'Просмотреть файл',
		article: 'Артикул',
		name: 'Наименование',
		brand: 'Бренд',
		article1: 'Артикул.1',
		quantity: 'Кол-во',
		price: 'Цена',
		batch: 'Партия',
		newPrice: 'Цена с лого',
		bestPrice: 'Лучшая цена',
		logo: 'Лого',
		deliveryTime: 'Срок поставки',
		linesOnPage: 'Строк на странице:',
		NDS: 'НДС',
		ApplyVATCalculation: 'Применить расчёт',
		priceAfterCalculation: 'Цена после расчёта',
	},
	EN: {
		history: 'History',
		date: 'Date',
		filters: 'Filters',
		dataBeforeParsing: 'Data before parsing',
		dataAfterParsing: 'Data after parsing',
		downloadFile: 'Download file',
		viewFile: 'View file',
		article: 'Article',
		name: 'Name',
		brand: 'Brand',
		article1: 'Article.1',
		quantity: 'Quantity',
		price: 'Price',
		batch: 'Batch',
		newPrice: 'Logo price',
		bestPrice: 'Best price',
		logo: 'Logo',
		deliveryTime: 'Delivery time',
		linesOnPage: 'Lines on the page:',
		NDS: 'NDS',
		ApplyVATCalculation: 'Apply calculation',
		priceAfterCalculation: 'Price after calculation',
	},
}
export const dashboardTexts = {
	RU: {
		edit: 'Редактировать',
		remove: 'Удалить',
		add: 'Добавить',
		fullName: 'Фамилия Имя Отчество',
		description: 'Описание',
		login: 'Логин',
		password: 'Пароль',
		isAdmin: 'Администратор/Пользователь',
		admin: 'Администратор',
		simpleUser: 'Пользователь',
		save: 'Сохранить',
		cancel: 'Отменить',
		userData: 'Данные пользователя',
		newLogin: 'Логин:',
		newPassword: 'Пароль:',
	},
	EN: {
		edit: 'Edit',
		remove: 'Remove',
		add: 'Add',
		fullName: 'Surname Name',
		description: 'Description',
		login: 'Login',
		password: 'Password',
		isAdmin: 'Administrator/User',
		admin: 'Administrator',
		simpleUser: 'User',
		save: 'Save',
		cancel: 'Cancel',
		userData: 'User data',
		newLogin: 'Login:',
		newPassword: 'Password:',
	},
}
export const settingsTexts = {
	RU: {
		PROXY: 'ПРОКСИ',
		FILTERS: 'ФИЛЬТРЫ',
		proxyInCard: 'прокси',
		quantity: 'Количество',
		duration: 'Длительность аренды',
		buy: 'Купить',
		toExtend: 'Продлить',
		remove: 'Удалить',
		logo: 'Лого -',
		deliveryTime: 'Срок поставки -',
		original: 'Оригинал -',
		depthOfAnalogueSearch: 'Глубина поиска аналога -',
		depthOfSelectionByTheFirstFilter: 'Глубина отбора по первому фильтру -',
		title: 'Заголовок -',
		save: 'Сохранить',
		contain: 'Содержит',
		notContain: 'Не содержит',
		moreThan: 'Больше чем',
		lessThan: 'Меньше чем',
		originals: 'Оригиналы',
		notOriginals: 'Оригиналы и не оригиналы',
		pickup_point: 'Пункт самовывоза',
		uploadProxy: 'Загрузить прокси',
		uploadProxyModalTitle: 'Загрузить прокси из файла',
		sameBrandAnalog: 'Аналоги того же производителя',include:"Включать",notInclude:"Не включать"
	},
	EN: {
		PROXY: 'PROXY',
		FILTERS: 'FILTERS',
		proxyInCard: 'proxy',
		quantity: 'Quantity',
		duration: 'Duration',
		buy: 'Buy',
		toExtend: 'To extend',
		remove: 'Remove',
		logo: 'Logo -',
		deliveryTime: 'Delivery time -',
		original: 'Original -',
		depthOfAnalogueSearch: 'Depth of analogue search -',
		depthOfSelectionByTheFirstFilter:
			'Depth of selection by the first filter -',
		title: 'Title -',
		save: 'Save',
		contain: 'Contain',
		notContain: 'Not contain',
		moreThan: 'More than',
		lessThan: 'Less than',
		originals: 'Originals',
		notOriginals: 'Originals and non-originals',
		pickup_point: 'Pickup point',
		uploadProxy: 'Upload proxy',
		sameBrandAnalog: 'Analogs of the same manufacturer',
		uploadProxyModalTitle: 'Upload proxy from file',include:"Include",notInclude:"Not include"
	},
}

export const statusMessages = {
	RU: {
		PARSING_COMPLETED: 'Товары спаршены, подождите, идет сохранение',
		ALL_PROXIES_BANNED:
			'Все прокси забанены, подождите, идет редактирование',
		PARSER_NOT_STARTED_DATA_SAVED: 'Парсер не запущен | Данные сохранены',
		PARSER_RUNNING: 'Парсер работает',
		ALL_PROXY_ARE_BLOCKED: 'Все прокси заблокированы',
	},
	EN: {
		PARSING_COMPLETED: 'Items parsed, please wait, saving in progress',
		ALL_PROXIES_BANNED:
			'All proxies banned, please wait, editing in progress',
		PARSER_NOT_STARTED_DATA_SAVED: 'Parser not started | Data saved',
		PARSER_RUNNING: 'Parser is running',
		ALL_PROXY_ARE_BLOCKED: 'All proxies are blocked',
	},
}
